{
  imports = [
    ./packages.nix
    ./bash.nix
    ./git.nix
    ./gh.nix
    ./ripgrep.nix
    ./fzf.nix
    ./kitty.nix
    ./neovim
    ./tmux.nix
    ./direnv.nix
    ./starship.nix
    ./firefox.nix
    ./claude.nix
    ./google-chrome.nix
    ./ssh.nix
    ./niri.nix
    ./waybar.nix
    ./remote-desktop.nix
  ];
}
